# Site settings
# These are used to personalize your site. You access them via {{ site.title }}, 
# {{ site.email }} and so on. You can create any custom variable you like. They
# will be accessible in the templates via {{ site.myvariable }}.

title: RichTextKit
description: >-
  "RichTextKit ..."

url: https://richtextkit.com
email: info@richtextkit.com

is_lib: 1

copyright_year: 2025
copyright_owner: Kankoda Sweden AB
copyright_url: https://kankoda.com

bluesky_username: richtextkit.bsky.social
github_username: Kankoda
mastodon_username: richtextkit@techhub.social
twitter_username: richtextkitsdk

assets: /assets/
header_image: /assets/icon/icon-header.png
header_image_type: icon
header_title: RichTextKit

urls:
  email:      mailto:info@richtextkit.com
  rss:        https://richtextkit.com/feed.xml

  blog:       /blog
  bluesky:    https://bsky.app/profile/richtextkit.bsky.social
  docs:       https://danielsaidi.github.io/RichTextKit/
  # docs_pro:   https://kankoda.github.io/RichTextKit/
  github:     https://github.com/danielsaidi/richtextkit
  # github_pro: https://github.com/kankoda/richtextkitpro
  mastodon:   https://techhub.social/@richtextkit
  twitter:    https://twitter.com/richtextkitsdk

  swift:      https://www.swift.org
  swiftui:    https://developer.apple.com/xcode/swiftui/

header_pages:
  - pages/home.md
  - pages/github.md
  - pages/blog.md

footer_sitemap:
  - pages/home.md
  - pages/about.md
  - pages/blog.md

collections_dir: collections

collections:
  features:
    output: true
    permalink: /features/:name/
  posts:
    output: true
    permalink: /blog/:categories/:year/:month/:day/:title

defaults:
  -
    scope:
      type: "pages"
    values:
      hero: ""
      layout: "page"
  -
    scope:
      type: "posts"
    values:
      author: "danielsaidi"
      layout: "post"
      image:  /assets/headers/icon.jpg

baseurl: ""
theme: minima
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-redirect-from

exclude:
  - Gemfile
  - Gemfile.lock